org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version_range=[1.21.1]
neo_version=21.1.228
neo_version_range=[21.1.0,)
loader_version_range=[1,)

mod_id=tetratic_combat_expanded
mod_name=Tetratic Combat Expanded
mod_license=MIT
mod_version=2.8.3-1.21.1
mod_group_id=smartin.tetraticcombat
mod_authors=Firelight Studios (BluSpring, Kiran), Smartin, Ace
mod_description=Tetra compatibility with Better Combat.

tetra_version=1.21.1-6.13.0
tetra_version_range=[6.13.0,)
mutil_version=1.21.1-6.3.1
mutil_version_range=[6.3.1,)
better_combat_version=VhIOvcXP
better_combat_version_range=[2.4.0,)
